### PR TITLE
Create Vwarhem.json

### PR DESCRIPTION
**Pull request by Victorwarhem**

### CODE REVIEW

**Comment by floswald** [comment]
hi @Victorwarhem,

you should save the file in the folder `_data/spring2016`, as in the example. thanks!

**Comment by floswald** [comment]
hi. your tests fail. click on "details" next to the Travis-CI line above to find out why.

**Comment by Victorwarhem** [comment]
Sorry but I don't understand what went wrong. Is it when I submitted the doc to the repo?

**Comment by floswald** [comment]
several things. looking at your fork, there are at least 3 files around. you just need one. 

1. the file needs to be like your username. that's `Victorwarhem.json`.
2. the file needs to be saved in the specified folder. 
3. there is a file in the right location, but it has the wrong name (point 1.)
4. look at that file and compare it with my example. can you see the difference? that's what is wrong.

**Comment by floswald** [comment]
:+1:

**Comment by Victorwarhem** [comment]
Thanks!

**Pull request merged**
